from selenium import webdriver
from selenium.common.exceptions import *
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
import time

class Practise():
    def test(self):
        driver = webdriver.Chrome()
        driver.maximize_window()
        driver.get("https://letskodeit.teachable.com/p/practice")
        driver.implicitly_wait(10)
        print("first website title is : ", str(driver.title))
        print("first website url is : ", str(driver.current_url))
        driver.find_element_by_id("openwindow").click()
        print("total_windows : " + str(driver.window_handles))
        driver.switch_to.window(driver.window_handles[1])
        print("first_window_name: " + str(driver.window_handles[0]))
        print("second_window_name: "+ str(driver.current_window_handle))
        driver.maximize_window()
        print("second website title is : ", str(driver.title))
        print("second website url is : ", str(driver.current_url))
        driver.find_element_by_id("search-courses").send_keys("python", Keys.ENTER)
        time.sleep(5)
        driver.find_element_by_id("search-courses").clear()
        time.sleep(5)
        driver.close()
        time.sleep(5)
        driver.switch_to.window(driver.window_handles[0])
        iframe = driver.find_element_by_xpath("//legend[text()='iFrame Example']")
        webdriver.ActionChains(driver).move_to_element(iframe).perform()
        time.sleep(5)
        driver.switch_to.frame("courses-iframe")
        driver.find_element_by_id("search-courses").send_keys("python", Keys.ENTER)
        time.sleep(10)
        driver.find_element_by_id("search-courses").clear()
        time.sleep(3)
        driver.switch_to.default_content()
        switch_alert = driver.find_element_by_xpath("//legend[text()='Switch To Alert Example']")
        webdriver.ActionChains(driver).move_to_element(switch_alert).perform()
        driver.find_element_by_name("enter-name").send_keys("Mahesh")
        driver.find_element_by_id("alertbtn").click()
        time.sleep(3)
        driver.switch_to.alert.accept()
        time.sleep(3)
        driver.find_element_by_name("enter-name").send_keys("Mahesh")
        driver.find_element_by_id("confirmbtn").click()
        time.sleep(3)
        driver.switch_to.alert.accept()
        time.sleep(3)
        driver.find_element_by_name("enter-name").send_keys("Mahesh")
        driver.find_element_by_id("confirmbtn").click()
        time.sleep(3)
        driver.switch_to.alert.dismiss()
        time.sleep(3)
        driver.execute_script("window.scrollBy(0,900);")
        mouse_hover = driver.find_element_by_id("mousehover")
        ActionChains(driver).move_to_element(mouse_hover).perform()
        Top = driver.find_element_by_xpath("//a[text()='Top']")
        webdriver.ActionChains(driver).move_to_element(Top).click().perform()
        time.sleep(5)
        webdriver.ActionChains(driver).move_to_element(mouse_hover).perform()
        Reload = driver.find_element_by_xpath("//a[text()='Reload']")
        webdriver.ActionChains(driver).move_to_element(Reload).click().perform()
        time.sleep(5)
        driver.execute_script("window.open('https://jqueryui.com/');")
        print("third website title is : ", str(driver.title))
        print("third website url is : ", str(driver.current_url))
        time.sleep(10)
        driver.switch_to.window(driver.window_handles[1])
        driver.find_element_by_xpath("//a[text()='Droppable']").click()
        driver.switch_to.frame(0)
        draggable = driver.find_element_by_id("draggable")
        droppable = driver.find_element_by_id("droppable")
        webdriver.ActionChains(driver).drag_and_drop(draggable, droppable).perform()
        time.sleep(10)
        driver.execute_script("window.open('https://jqueryui.com/');")
        print("fourth website title is : ", str(driver.title))
        print("fourth website url is : ", str(driver.current_url))
        time.sleep(10)
        driver.switch_to.window(driver.window_handles[2])
        slider = driver.find_element_by_xpath("//a[text()='Slider']")
        webdriver.ActionChains(driver).move_to_element(slider).click().perform()
        driver.switch_to.frame(0)
        slider_element = driver.find_element_by_xpath("//span[@tabindex='0']")
        webdriver.ActionChains(driver).drag_and_drop_by_offset(slider_element,200,0)
        time.sleep(10)
        driver.switch_to.window(driver.window_handles[0])
        checkboxes = driver.find_elements_by_xpath("//input[@type='checkbox']")
        for check in checkboxes:
            is_selected = check.is_selected()
            if not is_selected:
                check.click()
                time.sleep(3)
        radioboxes = driver.find_elements_by_xpath("//input[@type='radio']")
        for radio in radioboxes:
            is_selected = radio.is_selected()
            if not is_selected:
                radio.click()
                time.sleep(3)
        time.sleep(5)
        driver.switch_to.window(driver.window_handles[1])
        driver.switch_to.default_content()
        driver.find_element_by_xpath("//a[text()='Resizable']").click()
        time.sleep(5)
        file_name = "D:\screenshots\check.png"
        driver.save_screenshot(file_name)
        time.sleep(10)
        driver.quit()

b=Practise()
b.test()